name: CI/CD

permissions:
  contents: write

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Run ESLint
        run: npm run lint

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Check formatting with Prettier
        run: npm run format

  type-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Run TypeScript type checking
        run: npm run typecheck

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20, 22]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run tests with coverage
        run: npm run test:coverage

      - name: Upload coverage reports to Codecov
        if: matrix.node-version == 20
        uses: codecov/codecov-action@v5
        with:
          file: ./coverage/coverage-final.json
          fail_ci_if_error: false
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  build:
    needs: [lint, format, type-check, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Build package
        run: npm run build

      - name: Check build output
        run: |
          ls -la dist/
          echo "Checking that all expected files are present:"
          test -f dist/index.cjs || (echo "Missing index.cjs" && exit 1)
          test -f dist/index.mjs || (echo "Missing index.mjs" && exit 1)
          test -f dist/index.d.ts || (echo "Missing index.d.ts" && exit 1)
          test -f dist/index.d.cts || (echo "Missing index.d.cts" && exit 1)
          echo "All build files present ✓"

      - name: Test package exports
        run: |
          echo "Testing package imports..."
          node -e "import('./dist/index.mjs').then(pkg => console.log('ESM import works:', Object.keys(pkg).length > 0))"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/
          retention-days: 7

      - name: Upload package-lock
        uses: actions/upload-artifact@v4
        with:
          name: package-lock
          path: package-lock.json
          retention-days: 7

  security-audit:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Download package-lock
        uses: actions/download-artifact@v4
        with:
          name: package-lock

      - name: Run security audit
        run: npm audit --audit-level=moderate

  auto-version:
    needs: [build, security-audit]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./.github/actions/setup
        with:
          node-version: '20'
          cache: 'npm'

      - name: Configure Git
        run: |
          git config --local user.email "m@rco.sh"
          git config --local user.name "Marco Antonio Gonzalez Junior"

      - name: Determine version bump type
        id: version-type
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          echo "Commit message: $COMMIT_MSG"
          COMMIT_MSG_LOWER=$(echo "$COMMIT_MSG" | tr '[:upper:]' '[:lower:]')
          if echo "$COMMIT_MSG_LOWER" | grep -E "\[skip version\]" > /dev/null; then
            echo "Skipping version bump due to [skip version] in commit message"
            echo "skip=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          if echo "$COMMIT_MSG_LOWER" | grep -E "(bug|fix)" > /dev/null; then
            VERSION_TYPE="patch"
          elif echo "$COMMIT_MSG_LOWER" | grep -E "release" > /dev/null; then
            VERSION_TYPE="major"
          else
            VERSION_TYPE="minor"
          fi
          echo "Version bump type: $VERSION_TYPE"
          echo "version-type=$VERSION_TYPE" >> $GITHUB_OUTPUT
          echo "skip=false" >> $GITHUB_OUTPUT

      - name: Bump version and create tag
        id: version-bump
        if: steps.version-type.outputs.skip == 'false'
        run: |
          echo "Bumping version with type: ${{ steps.version-type.outputs.version-type }}"
          npm version ${{ steps.version-type.outputs.version-type }} --no-git-tag-version
          NEW_VERSION=$(node -p "require('./package.json').version")
          echo "New version: $NEW_VERSION"
          git add package.json package-lock.json
          git commit -m "chore: bump version to $NEW_VERSION [skip ci]"
          git tag "v$NEW_VERSION"
          git push origin main --follow-tags || echo "Push failed, check branch protection rules"

  publish-npm:
    needs: [auto-version]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: dist/

      - name: Fix package
        run: npm pkg fix

      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-gpr:
    needs: [auto-version]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: dist/

      - name: Fix package
        run: npm pkg fix

      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  create-release:
    needs: [publish-npm, publish-gpr]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v$(node -p "require('./package.json').version")
          release_name: v$(node -p "require('./package.json').version")
          body: |
            Please refer to the commit history for changes.
          draft: false
          prerelease: false